name: Rust checks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libasound2-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev
      - name: Test pull request
        if: github.event_name == 'pull_request'
        run: cargo test -- --skip app::ui::tests::creates_playlist_through_the_ui
      - name: Test main including UI
        if: github.event_name == 'push'
        run: cargo test
